#!/bin/bash

FILE=/tmp/httppid

if [ $1 = '--start' ]; then
    if [ -f "$FILE" ]; then

        notify-send -i network-warning-symbolic-dark "Detenga primero el servidor"

    else
        DIRECTIP=$(hostname -I | awk '{print $1}')
        
        notify-send -i network 'Compartir por HTTP' "La direccion es: http://$DIRECTIP:8000/"
        
        cd $2
    
        python -m SimpleHTTPServer &  echo $! > /tmp/httppid
    fi
else
    PID=`cat $FILE`
    kill $PID
    rm $FILE
    notify-send -i network "Se ha detenido el servidor"
fi
    
